### PR TITLE
Preparing for Gitpod's restart workspace bug fix to get into production

### PR DESCRIPTION
**Pull request by shaal**
At the end of March / beginning of April, the bug fix for https://www.github.com/gitpod-io/gitpod/issues/3174 should be available in production.

This PR runs ddev and composer as part of `init`, to prepare everything in advance, during prebuild, to allow workspace to start much faster.

It then runs ddev and composer again, to apply any changes when a workspace gets opened again.

### CODE REVIEW

**Review by rfay — COMMENTED** [review]
Looks right to me.

**Comment by shaal** [comment]
@rfay something is not right. Can you test it? In the existing gitpod, this should run as new workspace, but should fail when restarting workspace.

**Comment by rfay** [comment]
It doesn't work for me, but neither does master. On master, I can never get a working bash prompt. although I can do a d9 install

**Comment by rfay** [comment]
Oh, but my installation also froze. I imagine  I don't see anything on https://status.gitpod.io/ but things sure look bad.

**Comment by shaal** [comment]
I think it is because of wrong configuration / indentation / comments inside `.gitpod.yml`

**Comment by rfay** [comment]
Why do you think the master version isn't working?

**Comment by shaal** [comment]
> Why do you think the master version isn't working?

I think there's no problem with the master version.

**Pull request closed without merging**
